// Generated by CoffeeScript 1.10.0
(function() {
  var Twitter;

  Twitter = require('twitter');

  module.exports = function() {
    var accessTokenKey, accessTokenSecret, consumerKey, consumerSecret, status, twitter;
    status = process.argv[2];
    if (status == null) {
      throw new Error('bbn-t <status>');
    }
    consumerKey = process.env.BBN_T_CONSUMER_KEY;
    consumerSecret = process.env.BBN_T_CONSUMER_SECRET;
    accessTokenKey = process.env.BBN_T_ACCESS_TOKEN;
    accessTokenSecret = process.env.BBN_T_ACCESS_TOKEN_SECRET;
    twitter = new Twitter({
      consumer_key: consumerKey,
      consumer_secret: consumerSecret,
      access_token_key: accessTokenKey,
      access_token_secret: accessTokenSecret
    });
    return twitter.post('statuses/update', {
      status: status
    }, function(err, result) {
      var id_str, text, user;
      if (err != null) {
        return console.error(err);
      } else {
        user = result.user, id_str = result.id_str, text = result.text;
        return console.log("https://twitter.com/" + user.name + "/status/" + id_str + "\n" + text);
      }
    });
  };

}).call(this);
